import {
  View, StyleSheet, FlatList, TouchableOpacity,
  ActivityIndicator, RefreshControl, Linking, ScrollView, Image, Alert,
} from "react-native";
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { SafeAreaView } from "react-native-safe-area-context";
import { useTheme, useThemedStyles } from "../../theme";
import { colors } from "../../constants/colors";
import { Text } from "../../components/ui";
import { api } from "../../lib/api";
import { ApiResponseError, apiRequest, formatApiError } from "../../lib/http";
import { useRouter } from "expo-router";
import * as Haptics from "expo-haptics";
import {
  RedditLogoIcon, NewspaperIcon, FlameIcon, ArrowSquareOutIcon,
  SparkleIcon, PlusIcon, CaretDownIcon, CaretUpIcon,
} from "phosphor-react-native";
import { XLogoIcon } from "../../components/XLogoIcon";

const NICHES = ["tech", "finance", "fitness", "beauty", "food", "gaming", "travel", "fashion", "business", "crypto", "lifestyle", "sports"];
const MAIN_CANVAS_LABEL = "Main Canvas";

// Test card — inject at top of list to verify UI changes without hitting the API
const TEST_TWEET: TrendRow = {
  id: "test-tweet-001",
  platform: "x",
  platformDisplay: "X",
  title: "Just shipped: we trained a model entirely on synthetic data generated by the previous model, and it outperformed the human-labeled baseline on 7 out of 9 benchmarks. The bootstrapping flywheel is real. Thread 🧵",
  summary: "A team just published results showing a self-improving data flywheel where each model generation produces better synthetic training data than the last. Benchmark scores climbed across coding, reasoning, and math tasks. The key insight: diversity of the synthetic prompts matters more than volume. They're open-sourcing the pipeline next week.",
  url: "https://x.com/testuser/status/1234567890",
  thumbnailUrl: null,
  author: "@researchlead",
  engagementScore: 4200,
};

type TrendRow = {
  id?: string;
  platform: string;
  platformDisplay?: string;
  title: string;
  summary?: string | null;
  url?: string | null;
  thumbnailUrl?: string | null;
  author?: string | null;
  engagementScore?: number | null;
};

type TodayXNewsGroup = {
  headline: TrendRow;
  relatedPosts: TrendRow[];
};

type InspirationCreateResponse = {
  inspiration?: { id: string };
  canvas?: {
    id: string;
    name: string;
    target: "main" | "explicit" | "fallback_main";
  } | null;
};

function urlDomain(url?: string | null): string | null {
  if (!url) return null;
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return null;
  }
}

function stripMarkdown(text: string): string {
  return text.replace(/\*\*/g, "").replace(/^\s*[-*•]\s+/gm, "").trim();
}

function displaySummary(item: TrendRow): string | null {
  const raw = item.summary?.trim();
  if (raw) return stripMarkdown(raw);
  // Don't fall back to "Author · domain" metadata — the platform badge already shows source
  return null;
}

function formatEngagement(score?: number | null): string | null {
  if (!score || score <= 0) return null;
  if (score >= 1000) return `${(score / 1000).toFixed(1)}k`;
  return String(score);
}

function trendItemKey(item: TrendRow): string {
  return item.url ?? item.id ?? `${item.platform}-${item.title}`;
}

function TrendCard({
  item,
  onAddToCanvas,
  onRemix,
  isAdding = false,
  addDisabled = false,
  compact = false,
  styles,
}: {
  item: TrendRow;
  onAddToCanvas: () => void;
  onRemix: () => void;
  isAdding?: boolean;
  addDisabled?: boolean;
  compact?: boolean;
  styles: ReturnType<typeof makeTrendingStyles>;
}) {
  const theme = useTheme();
  const [expanded, setExpanded] = useState(false);
  const isReddit = item.platform === "reddit";
  const isX = item.platform === "x";
  const platformColor = isReddit ? colors.reddit : isX ? theme.text : colors.news;
  const platformLabel =
    item.platformDisplay ?? (isReddit ? "Reddit" : isX ? "X" : "News");
  const summary = displaySummary(item);
  const engagement = formatEngagement(item.engagementScore);

  const titleLines = expanded ? undefined : (compact ? 2 : 3);
  const summaryLines = expanded ? undefined : 2;

  return (
    <View style={[styles.card, compact && styles.cardCompact]}>
      {item.thumbnailUrl ? (
        <Image
          source={{ uri: item.thumbnailUrl }}
          style={[styles.thumbnail, compact && styles.thumbnailCompact]}
          resizeMode="cover"
          accessibilityLabel="Post preview"
        />
      ) : null}

      <View style={[styles.cardBody, !item.thumbnailUrl && styles.cardBodyNoPad]}>
        <View style={styles.cardTop}>
          <View style={styles.platformRow}>
            {isX ? (
              <XLogoIcon size={16} color={platformColor} />
            ) : isReddit ? (
              <RedditLogoIcon size={16} color={platformColor} weight="fill" />
            ) : (
              <NewspaperIcon size={16} color={platformColor} weight="fill" />
            )}
            <Text style={[styles.platformLabel, { color: platformColor }]}>
              {platformLabel}
            </Text>
          </View>
          {engagement ? (
            <View style={styles.scoreBadge}>
              <FlameIcon size={12} color={colors.warning} weight="fill" />
              <Text style={styles.scoreText}>{engagement}</Text>
            </View>
          ) : null}
        </View>

        <TouchableOpacity
          onPress={() => { setExpanded((e) => !e); Haptics.selectionAsync(); }}
          activeOpacity={0.85}
        >
          <Text style={styles.cardTitle} numberOfLines={titleLines}>
            {stripMarkdown(item.title)}
          </Text>
        </TouchableOpacity>

        {summary ? (
          <TouchableOpacity
            onPress={() => { setExpanded((e) => !e); Haptics.selectionAsync(); }}
            activeOpacity={0.85}
          >
            <Text style={styles.cardSummary} numberOfLines={summaryLines}>
              {summary}
            </Text>
          </TouchableOpacity>
        ) : null}

        <TouchableOpacity
          onPress={() => { setExpanded((e) => !e); Haptics.selectionAsync(); }}
          style={styles.expandToggle}
        >
          <Text style={styles.expandToggleText}>
            {expanded ? "Show less" : "Show more"}
          </Text>
        </TouchableOpacity>

        <View style={styles.cardActions}>
          <TouchableOpacity
            style={[styles.addBtn, addDisabled && styles.addBtnDisabled]}
            onPress={onAddToCanvas}
            disabled={addDisabled}
          >
            {isAdding ? (
              <ActivityIndicator size="small" color={theme.success} />
            ) : (
              <PlusIcon size={14} color={theme.success} weight="bold" />
            )}
            <Text style={styles.addBtnText}>{isAdding ? "Saving..." : "Save to Main"}</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.remixBtn} onPress={onRemix}>
            <SparkleIcon size={14} color={theme.buttonSuccessText} weight="fill" />
            <Text style={styles.remixBtnText}>Remix</Text>
          </TouchableOpacity>
          {item.url ? (
            <TouchableOpacity onPress={() => Linking.openURL(item.url!)}>
              <ArrowSquareOutIcon size={18} color={theme.placeholderText} />
            </TouchableOpacity>
          ) : null}
        </View>
      </View>
    </View>
  );
}

function TodayXNewsSection({
  groups,
  onAddToCanvas,
  onRemix,
  addingKey,
  styles,
}: {
  groups: TodayXNewsGroup[];
  onAddToCanvas: (item: TrendRow) => void;
  onRemix: (item: TrendRow) => void;
  addingKey: string | null;
  styles: ReturnType<typeof makeTrendingStyles>;
}) {
  const theme = useTheme();
  const [expanded, setExpanded] = useState<Record<number, boolean>>({ 0: true });

  if (!groups.length) return null;

  return (
    <View style={styles.todaySection}>
      <View style={styles.todayHeader}>
        <XLogoIcon size={18} color={theme.text} />
        <Text style={styles.todayTitle}>Today&apos;s X News</Text>
      </View>

      {groups.map((group, idx) => {
        const isOpen = expanded[idx] ?? false;
        return (
          <View key={group.headline.url ?? group.headline.id ?? idx} style={styles.todayGroup}>
            <TouchableOpacity
              style={styles.todayHeadlineRow}
              onPress={() => {
                setExpanded((e) => ({ ...e, [idx]: !isOpen }));
                Haptics.selectionAsync();
              }}
            >
              <Text style={styles.todayHeadline} numberOfLines={2}>
                {stripMarkdown(group.headline.title)}
              </Text>
              {isOpen ? (
                <CaretUpIcon size={18} color={theme.textSupporting} />
              ) : (
                <CaretDownIcon size={18} color={theme.textSupporting} />
              )}
            </TouchableOpacity>

            {isOpen ? (
              <View style={styles.relatedList}>
                {group.relatedPosts.length === 0 ? (
                  <TrendCard
                    item={group.headline}
                    compact
                    styles={styles}
                    onAddToCanvas={() => onAddToCanvas(group.headline)}
                    onRemix={() => onRemix(group.headline)}
                    isAdding={addingKey === trendItemKey(group.headline)}
                    addDisabled={addingKey !== null}
                  />
                ) : null}
                {group.relatedPosts.map((rel, rIdx) => (
                  <TrendCard
                    key={rel.url ?? rel.id ?? rIdx}
                    item={rel}
                    compact
                    styles={styles}
                    onAddToCanvas={() => onAddToCanvas(rel)}
                    onRemix={() => onRemix(rel)}
                    isAdding={addingKey === trendItemKey(rel)}
                    addDisabled={addingKey !== null}
                  />
                ))}
              </View>
            ) : null}
          </View>
        );
      })}
    </View>
  );
}

export default function TrendingScreen() {
  const router = useRouter();
  const qc = useQueryClient();
  const theme = useTheme();
  const styles = useThemedStyles(makeTrendingStyles);
  const [selectedNiche, setSelectedNiche] = useState("tech");
  const [addingKey, setAddingKey] = useState<string | null>(null);

  const { data, isLoading, refetch, error: trendsError } = useQuery({
    queryKey: ["trends", selectedNiche],
    queryFn: async () => {
      try {
        const d = await apiRequest<any>("GET", `/api/trends?niche=${selectedNiche}`, () =>
          api.trends.$get({ query: { niche: selectedNiche } })
        );
        return {
          trends: (d?.trends ?? []) as TrendRow[],
          todayXNews: (d?.todayXNews ?? []) as TodayXNewsGroup[],
          limitReached: false,
          message: "",
        };
      } catch (err) {
        if (
          err instanceof ApiResponseError &&
          err.status === 403 &&
          err.body &&
          typeof err.body === "object" &&
          "limitReached" in err.body
        ) {
          const body = err.body as { message?: string; limitReached?: boolean };
          return {
            trends: [] as TrendRow[],
            todayXNews: [] as TodayXNewsGroup[],
            limitReached: true,
            message: body.message ?? "Daily trend limit reached. Upgrade to Premium.",
          };
        }
        throw err;
      }
    },
  });

  async function handleAddToCanvas(item: TrendRow) {
    const itemKey = trendItemKey(item);
    if (addingKey) return;

    setAddingKey(itemKey);
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    console.log("[CanvasAdd] start", {
      itemKey,
      platform: item.platform,
      url: item.url ?? null,
      target: MAIN_CANVAS_LABEL,
    });

    try {
      const result = await apiRequest<InspirationCreateResponse>("POST", "/api/inspirations", () =>
        api.inspirations.$post({
          json: {
            rawContent: `${stripMarkdown(item.title)}\n\n${displaySummary(item) || ""}`,
            sourceUrl: item.url,
            sourcePlatform: item.platform,
            type: "text",
            title: stripMarkdown(item.title),
            ogImage: item.thumbnailUrl ?? null,
            attachToMainCanvas: true,
          },
        })
      );
      await qc.invalidateQueries({ queryKey: ["inspirations"] });
      await qc.invalidateQueries({ queryKey: ["canvases"] });
      const canvasName = result.canvas?.name ?? MAIN_CANVAS_LABEL;
      console.log("[CanvasAdd] success", {
        itemKey,
        canvasName,
        target: result.canvas?.target ?? "main",
      });
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      Alert.alert("Saved", `Added to ${canvasName}`);
    } catch (err) {
      console.error("[CanvasAdd] failed", {
        itemKey,
        message: err instanceof Error ? err.message : "Unknown error",
      });
      Alert.alert("Add to canvas failed", formatApiError(err, "Could not save trend"));
    } finally {
      setAddingKey(null);
    }
  }

  const handleRemix = async (item: TrendRow) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    try {
      const d = await apiRequest<{ inspiration?: { id: string } }>("POST", "/api/inspirations", () =>
        api.inspirations.$post({
          json: {
            rawContent: `${stripMarkdown(item.title)}\n\n${displaySummary(item) || ""}`,
            sourceUrl: item.url,
            sourcePlatform: item.platform,
            type: "text",
            title: stripMarkdown(item.title),
            ogImage: item.thumbnailUrl ?? null,
          },
        })
      );
      if ("inspiration" in d && d.inspiration?.id) {
        qc.invalidateQueries({ queryKey: ["inspirations"] });
        router.push(`/remix/${d.inspiration.id}`);
      }
    } catch (err) {
      Alert.alert("Remix failed", formatApiError(err, "Could not create remix source"));
    }
  };

  const trends = [TEST_TWEET, ...(data?.trends ?? [])];
  const todayXNews = data?.todayXNews ?? [];
  const limitReached = data?.limitReached ?? false;
  const limitMessage = data?.message ?? "Daily trend limit reached. Upgrade to Premium.";
  const trendsErrorMessage = trendsError ? formatApiError(trendsError, "Could not load trends") : "";

  const ListHeader = (
    <>
      <TodayXNewsSection
        groups={todayXNews}
        styles={styles}
        onAddToCanvas={handleAddToCanvas}
        onRemix={handleRemix}
        addingKey={addingKey}
      />
      {todayXNews.length > 0 ? (
        <Text style={styles.sectionLabel}>Niche Trends</Text>
      ) : null}
    </>
  );

  return (
    <SafeAreaView style={styles.safe} edges={["top", "left", "right"]}>
      <View style={styles.header}>
        <Text preset="headline" style={styles.headerTitle}>Today&apos;s Trends</Text>
        <TouchableOpacity onPress={() => { refetch(); Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); }}>
          <Text style={styles.refreshText}>Refresh</Text>
        </TouchableOpacity>
      </View>

      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.nichesScroll} contentContainerStyle={styles.nichesContent}>
        {NICHES.map((n) => (
          <TouchableOpacity
            key={n}
            style={[styles.nicheChip, selectedNiche === n && styles.nicheChipActive]}
            onPress={() => { setSelectedNiche(n); Haptics.selectionAsync(); }}
          >
            <Text style={[styles.nicheChipText, selectedNiche === n && styles.nicheChipTextActive]}>
              {n.charAt(0).toUpperCase() + n.slice(1)}
            </Text>
          </TouchableOpacity>
        ))}
      </ScrollView>

      {limitReached ? (
        <View style={styles.limitBanner}>
          <Text style={styles.limitBannerTitle}>Daily trend limit reached</Text>
          <Text style={styles.limitBannerText}>{limitMessage}</Text>
        </View>
      ) : null}
      {trendsErrorMessage ? (
        <View style={styles.limitBanner}>
          <Text style={styles.limitBannerTitle}>Trend load failed</Text>
          <Text style={styles.limitBannerText}>{trendsErrorMessage}</Text>
        </View>
      ) : null}

      {isLoading ? (
        <View style={styles.centered}>
          <ActivityIndicator color={theme.success} size="large" />
          <Text style={styles.loadingText}>Fetching trends...</Text>
        </View>
      ) : trends.length === 0 && todayXNews.length === 0 && !limitReached ? (
        <View style={styles.centered}>
          <FlameIcon size={48} color={theme.placeholderText} />
          <Text style={styles.emptyTitle}>No trends found</Text>
          <Text style={styles.emptyText}>Try refreshing or switching niche</Text>
        </View>
      ) : (
        <FlatList
          data={trends}
          keyExtractor={(item) =>
            trendItemKey(item)
          }
          ListHeaderComponent={ListHeader}
          contentContainerStyle={styles.list}
          refreshControl={<RefreshControl refreshing={isLoading} onRefresh={refetch} tintColor={theme.success} />}
          renderItem={({ item }) => (
            <TrendCard
              item={item}
              styles={styles}
              onAddToCanvas={() => handleAddToCanvas(item)}
              onRemix={() => handleRemix(item)}
              isAdding={addingKey === trendItemKey(item)}
              addDisabled={addingKey !== null}
            />
          )}
        />
      )}
    </SafeAreaView>
  );
}

function makeTrendingStyles(theme: import("../../theme/types").ThemeColors) {
  return {
    safe: { flex: 1, backgroundColor: theme.appBG },
    header: { flexDirection: "row" as const, justifyContent: "space-between" as const, alignItems: "center" as const, paddingHorizontal: 16, paddingVertical: 12 },
    headerTitle: { color: theme.text },
    refreshText: { color: theme.success, fontSize: 14, fontWeight: "600" as const },
    nichesScroll: { flexGrow: 0 },
    nichesContent: { paddingHorizontal: 16, gap: 8, paddingBottom: 8 },
    limitBanner: {
      marginHorizontal: 16,
      marginBottom: 8,
      backgroundColor: `${theme.warning}1A`,
      borderWidth: 1,
      borderColor: `${theme.warning}66`,
      borderRadius: 12,
      padding: 12,
      gap: 4,
    },
    limitBannerTitle: { color: theme.warning, fontSize: 13, fontWeight: "700" as const },
    limitBannerText: { color: theme.textSupporting, fontSize: 12 },
    nicheChip: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 100, borderWidth: 1, borderColor: theme.border, backgroundColor: theme.cardBG },
    nicheChipActive: { backgroundColor: theme.success, borderColor: theme.success },
    nicheChipText: { color: theme.textSupporting, fontSize: 13, fontWeight: "500" as const },
    nicheChipTextActive: { color: theme.buttonSuccessText, fontWeight: "700" as const },
    centered: { flex: 1, alignItems: "center" as const, justifyContent: "center" as const, gap: 8 },
    loadingText: { color: theme.textSupporting, fontSize: 14 },
    emptyTitle: { color: theme.textSupporting },
    emptyText: { color: theme.placeholderText },
    list: { padding: 16, gap: 12, paddingBottom: 32 },
    sectionLabel: {
      color: theme.textSupporting,
      fontSize: 13,
      fontWeight: "700" as const,
      marginBottom: 8,
      marginTop: 4,
    },
    todaySection: { marginBottom: 16, gap: 10 },
    todayHeader: { flexDirection: "row" as const, alignItems: "center" as const, gap: 8, marginBottom: 4 },
    todayTitle: { color: theme.text, fontSize: 16, fontWeight: "700" as const },
    todayGroup: {
      backgroundColor: theme.cardBG,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      overflow: "hidden" as const,
    },
    todayHeadlineRow: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      justifyContent: "space-between" as const,
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 10,
    },
    todayHeadline: { flex: 1, color: theme.text, fontSize: 14, fontWeight: "600" as const, lineHeight: 20 },
    relatedList: { paddingHorizontal: 10, paddingBottom: 10, gap: 8 },
    card: { backgroundColor: theme.cardBG, borderRadius: 16, borderWidth: 1, borderColor: theme.border, overflow: "hidden" as const },
    cardCompact: { borderRadius: 12 },
    thumbnail: { width: "100%" as const, height: 160, backgroundColor: theme.highlightBG },
    thumbnailCompact: { height: 120 },
    cardBody: { padding: 14, gap: 8 },
    cardBodyNoPad: { paddingTop: 14 },
    cardTop: { flexDirection: "row" as const, justifyContent: "space-between" as const, alignItems: "center" as const },
    platformRow: { flexDirection: "row" as const, alignItems: "center" as const, gap: 6 },
    platformLabel: { fontSize: 12, fontWeight: "600" as const },
    scoreBadge: { flexDirection: "row" as const, alignItems: "center" as const, gap: 4, backgroundColor: theme.highlightBG, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 100 },
    scoreText: { color: theme.warning, fontSize: 11, fontWeight: "600" as const },
    cardTitle: { color: theme.text, fontSize: 15, fontWeight: "600" as const, lineHeight: 21 },
    cardSummary: { color: theme.textSupporting, fontSize: 13, lineHeight: 18 },
    expandToggle: { alignSelf: "flex-start" as const, paddingVertical: 2 },
    expandToggleText: { color: theme.placeholderText, fontSize: 12, fontWeight: "500" as const },
    cardActions: { flexDirection: "row" as const, alignItems: "center" as const, gap: 8, marginTop: 4 },
    addBtn: { flexDirection: "row" as const, alignItems: "center" as const, gap: 5, borderWidth: 1, borderColor: theme.success, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 100 },
    addBtnDisabled: { opacity: 0.6 },
    addBtnText: { color: theme.success, fontSize: 13, fontWeight: "600" as const },
    remixBtn: { flexDirection: "row" as const, alignItems: "center" as const, gap: 5, backgroundColor: theme.success, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 100 },
    remixBtnText: { color: theme.buttonSuccessText, fontSize: 13, fontWeight: "700" as const },
  };
}
