import { colors } from "./colors";
import type { ThemeColors } from "./types";

export const lightTheme: ThemeColors = {
  appBG: colors.productLight100,
  splashBG: colors.green400,
  highlightBG: colors.productLight200,
  border: colors.productLight400,
  borderFocus: colors.green400,
  icon: colors.productLight700,
  iconMenu: colors.green400,
  iconHovered: colors.productLight900,
  textSupporting: colors.productLight800,
  text: colors.productLight900,
  link: colors.blue600,
  linkHover: colors.blue500,
  buttonDefaultBG: colors.productLight400,
  buttonHoveredBG: colors.productLight500,
  buttonPressedBG: colors.productLight600,
  buttonSuccessText: colors.productLight100,
  danger: colors.red,
  dangerHover: colors.redHover,
  warning: colors.yellow400,
  success: colors.green400,
  successHover: colors.greenHover,
  successPressed: colors.greenPressed,
  transparent: colors.transparent,
  signInPage: colors.green800,
  componentBG: colors.productLight100,
  hoverComponentBG: colors.productLight300,
  activeComponentBG: colors.productLight400,
  heading: colors.productLight900,
  textLight: colors.white,
  textError: colors.red,
  modalBackground: colors.productLight100,
  cardBG: colors.productLight200,
  cardBorder: colors.productLight200,
  spinner: colors.productLight800,
  placeholderText: colors.productLight700,
  sidebar: colors.productLight100,
  sidebarHover: colors.productLight300,
  colorScheme: "light",
};

export const darkTheme: ThemeColors = {
  appBG: colors.productDark100,
  splashBG: colors.green400,
  highlightBG: colors.productDark200,
  border: colors.productDark400,
  borderFocus: colors.green400,
  icon: colors.productDark700,
  iconMenu: colors.green400,
  iconHovered: colors.productDark900,
  textSupporting: colors.productDark800,
  text: colors.productDark900,
  link: colors.blue300,
  linkHover: colors.blue100,
  buttonDefaultBG: colors.productDark400,
  buttonHoveredBG: colors.productDark500,
  buttonPressedBG: colors.productDark600,
  buttonSuccessText: colors.productLight100,
  danger: colors.red,
  dangerHover: colors.redHover,
  warning: colors.yellow400,
  success: colors.green400,
  successHover: colors.greenHover,
  successPressed: colors.greenPressed,
  transparent: colors.transparent,
  signInPage: colors.green800,
  componentBG: colors.productDark100,
  hoverComponentBG: colors.productDark300,
  activeComponentBG: colors.productDark400,
  heading: colors.productDark900,
  textLight: colors.productDark900,
  textError: colors.red,
  modalBackground: colors.productDark100,
  cardBG: colors.productDark200,
  cardBorder: colors.productDark200,
  spinner: colors.productDark800,
  placeholderText: colors.productDark700,
  sidebar: colors.productDark100,
  sidebarHover: colors.productDark300,
  colorScheme: "dark",
};
