/**
 * Spacing, sizing, and typography scale ported from Expensify variables.ts.
 */
export const variables = {
  bottomTabHeight: 72,
  componentSizeSmall: 28,
  componentSizeXSmall: 20,
  componentSizeNormal: 40,
  componentSizeMedium: 48,
  componentSizeLarge: 52,
  inputComponentSizeNormal: 40,
  spacing2: 8,
  spacing3: 12,
  spacing4: 16,
  spacing5: 20,
  componentBorderRadius: 8,
  componentBorderRadiusSmall: 4,
  componentBorderRadiusMedium: 6,
  componentBorderRadiusNormal: 8,
  componentBorderRadiusLarge: 16,
  componentBorderRadiusXLarge: 28,
  componentBorderRadiusCard: 20,
  componentBorderRadiusRounded: 24,
  componentBorderRadiusCircle: 999,
  buttonBorderRadius: 100,
  fontSizeSmall: 11,
  fontSizeExtraSmall: 9,
  fontSizeLabel: 13,
  fontSizeNormal: 15,
  fontSizeMedium: 16,
  fontSizeLarge: 17,
  fontSizeXLarge: 22,
  fontSizeXXLarge: 28,
  fontSizeXXXLarge: 32,
  fontSizeH1: 19,
  fontSizeH2: 19,
  fontSizeNormalHeight: 20,
  lineHeightXXXLarge: 32,
  lineHeightSizeH2: 24,
} as const;
